### ISSUE TITLE
Hello, how to call psnr.m

### ISSUE THREAD

**Issue by EnNaenna** [kirk86/wateramarking#3]
Sorry, I did not find the psnr called in the program. Excuse me, what should I do to achieve use psnr.m to get the numerical result of the peak signal to noise ratio, Thank you!!

**Comment by kirk86** [comment]
Hi, you can call `psnr.m` directly like this: `p = psnr(x, y)`. Here `x` and `y` are both images. One of them is clean and the other supposedly noisy. `p` will be the variable that stores the value of the psnr.

**Comment by viveka76** [comment]
Hi,I got an imwrite error
This is the error
Error using imwrite (line 467)
Unable to open file "D:\watermark-dwt-matlab-master\wateramarking-master\watermarked_images\1.png" for writing.  You might
not have write permission.

Error in dwt_svd (line 75)
        imwrite(uint8(watermarked_image), watermarked_images_dir, 'png');

**Comment by kirk86** [comment]
@viveka76 
I would check 2 things:
1) Does the path `D:\watermark-dwt-matlab-master\wateramarking-master\watermarked_images\1.png` and image exist?
2) simply change permissions to all images to 777

**Comment by viveka76** [comment]
Does the path D:\watermark-dwt-matlab-master\wateramarking-master\watermarked_images\1.png and image exist?
ANSWER:no path and image did'nt exist
simply change permissions to all images to 777
ANSWER:how to do that

**Comment by kirk86** [comment]
> ANSWER:no path and image did'nt exist

Read the answer by [GUSTAVO SILVA](https://www.mathworks.com/matlabcentral/fileexchange/41686-dwt-svd-robust-and-secure-watermarking-scheme) in the comments section

> ANSWER:how to do that

Maybe try googling how to change file permissions in windows and see what comes up
